### PR TITLE
arm arm arm arm

### PR DESCRIPTION
**Pull request by Bubba8291**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Bubba8291** [comment]
@Lennolium Do I have to do anything else before you add it?

**Comment by Lennolium** [comment]
> @Lennolium Do I have to do anything else before you add it?

You did everything needed, thanks! I'm just unsure right now: I could just rebuild the current (old) version with native arm support, or wait until I've finished the ground up new and polished new version with many bugfixes and added features etc. One question: why is the native arm support important to you? The current (old) x86_64 version also runs fine on newer m1/m2... macs with rosetta emulation.

Cheers 🥂

**Comment by Bubba8291** [comment]
> > @Lennolium Do I have to do anything else before you add it?
> 
> You did everything needed, thanks! I'm just unsure right now: I could just rebuild the current (old) version with native arm support, or wait until I've finished the ground up new and polished new version with many bugfixes and added features etc. One question: why is the native arm support important to you? The current (old) x86_64 version also runs fine on newer m1/m2... macs with rosetta emulation.
> 
> Cheers 🥂

@Lennolium  I recently got an M2 mac, and I have not and do not plan to install rosetta. As much as it helps, there is enough support for most applications now where rosetta is not as needed. Also, there isn't really a good way to check if a program is using rosetta or not when installed, so rosetta could theoretically be on with an application that supports native silicon chips.

I'll create a build.sh file separate for silicon macs later today too.

**Comment by Lennolium** [comment]
Alright, this seems reasonable. I thought Rosetta was pre-installed on macOS. I will compile for arm64 tomorrow morning. Give me half a day and a download link will be ready. 

Thank you for your answers and help!
I will close this pr when the file is up ☺️

> > > @Lennolium Do I have to do anything else before you add it?
> > 
> > 
> > You did everything needed, thanks! I'm just unsure right now: I could just rebuild the current (old) version with native arm support, or wait until I've finished the ground up new and polished new version with many bugfixes and added features etc. One question: why is the native arm support important to you? The current (old) x86_64 version also runs fine on newer m1/m2... macs with rosetta emulation.
> > Cheers 🥂
> 
> @Lennolium I recently got an M2 mac, and I have not and do not plan to install rosetta. As much as it helps, there is enough support for most applications now where rosetta is not as needed. Also, there isn't really a good way to check if a program is using rosetta or not when installed, so rosetta could theoretically be on with an application that supports native silicon chips.
> 
> I'll create a build.sh file separate for silicon macs later today too.

**Comment by Bubba8291** [comment]
@Lennolium Universal binary would require more tweaking since brew binaries are located in separate locations on silicon macs.

**Review by Lennolium — APPROVED** [review]
Really great work! Approved 😊
Native arm64 version is now downloadable from the release tab.

P.S. you will be automatically added to the acknowledgment section in the README.

**Pull request merged**
